import unittest
from unittest.mock import AsyncMock, patch

from providers.openai_client import OPENAI_CHAT_MODEL, is_reasoning_model, reasoning_kwargs
from bot.intent_dispatcher import chat_model_for_intent
from services import code_generator
from services.code_generator import (
    CODE_MODEL,
    IDEA_CODE_MODEL,
    code_generation_model,
    extract_unified_diff,
    select_code_generation_provider,
)


class CodeGeneratorOutputTests(unittest.TestCase):
    def test_code_generation_uses_gpt_6_astra(self):
        self.assertEqual(OPENAI_CHAT_MODEL, "gpt-6.1-sol")
        self.assertEqual(CODE_MODEL, "gpt-6-astra")

    def test_chat_roles_keep_distinct_reasoning_tiers(self):
        self.assertEqual(chat_model_for_intent("chat_tiny"), "gpt-6-luna")
        self.assertEqual(chat_model_for_intent("chat_light"), "gpt-6-luna")
        self.assertEqual(chat_model_for_intent("chat_standard"), "gpt-6-luna")
        self.assertEqual(chat_model_for_intent("chat"), "gpt-6.1-sol")
        self.assertEqual(chat_model_for_intent("chat_deep"), "gpt-6-astra")

    def test_gpt_6_reasoning_controls_match_model_capabilities(self):
        self.assertTrue(is_reasoning_model("gpt-6-astra"))
        self.assertEqual(reasoning_kwargs("gpt-6-luna", "none", responses=True), {"reasoning": {"effort": "none"}})
        self.assertEqual(reasoning_kwargs("gpt-6-astra", "high", responses=True), {"reasoning": {"effort": "high"}})
        self.assertEqual(reasoning_kwargs("gpt-6.1-sol", "none", responses=True), {})

    def test_explicit_fable_directive_selects_claude(self):
        for request in (
            "claude edit your code",
            "Fable, change the repository",
            "use Claude to refactor your routing",
            "have fable fix the bot source",
        ):
            with self.subTest(request=request):
                self.assertEqual(select_code_generation_provider(request), "claude")
                self.assertEqual(code_generation_model(request), "claude-fable-5-1")

    def test_mentions_about_claude_do_not_select_it_as_generator(self):
        self.assertEqual(
            select_code_generation_provider("change your code so Claude chat has a timeout"),
            "openai",
        )
        self.assertEqual(code_generation_model("change your code"), "gpt-6-astra")


class ProviderAwareCodeGenerationTests(unittest.IsolatedAsyncioTestCase):
    async def test_planned_idea_uses_low_cost_code_model_and_reviewed_context(self):
        diff = """diff --git a/bot/response_policy.py b/bot/response_policy.py
--- a/bot/response_policy.py
+++ b/bot/response_policy.py
@@ -1 +1 @@
-import re
+import re  # bounded retry
"""
        with patch.object(
            code_generator,
            "_candidate_paths",
            return_value=["bot/response_policy.py"],
        ), patch.object(
            code_generator,
            "_git_at",
            return_value="import re\n",
        ), patch.object(
            code_generator,
            "_generate_code_response",
            new=AsyncMock(return_value=(diff, IDEA_CODE_MODEL)),
        ) as generate:
            patch_text, metadata = await code_generator.generate_planned_idea_patch(
                "Implement reviewed retry plan",
                "a" * 40,
                context_paths=["bot/response_policy.py", "config.py"],
            )

        self.assertEqual(patch_text, diff)
        self.assertEqual(metadata["model"], IDEA_CODE_MODEL)
        self.assertEqual(metadata["context_files"], ["bot/response_policy.py"])
        self.assertEqual(generate.await_args.kwargs["model_override"], IDEA_CODE_MODEL)

    async def test_claude_directive_uses_fable_for_patch(self):
        diff = """diff --git a/bot/response_policy.py b/bot/response_policy.py
--- a/bot/response_policy.py
+++ b/bot/response_policy.py
@@ -1 +1 @@
-import re
+import re  # generated by fable
"""
        context = [("bot/response_policy.py", "import re\n")]
        with patch.object(
            code_generator,
            "plan_code_context",
            new=AsyncMock(return_value=(context, {"selection": "model_planner"})),
        ), patch.object(
            code_generator,
            "_generate_code_response",
            new=AsyncMock(return_value=(diff, "claude-fable-5-1")),
        ) as generate:
            patch_text, metadata = await code_generator.generate_code_patch(
                "claude edit your code", "a" * 40
            )

        self.assertEqual(patch_text, diff)
        self.assertEqual(metadata["provider"], "claude")
        self.assertEqual(metadata["model"], "claude-fable-5-1")
        self.assertEqual(generate.await_args.kwargs["provider"], "claude")

    def test_extracts_fenced_unified_diff(self):
        text = """Here is the patch:
```diff
diff --git a/bot/response_policy.py b/bot/response_policy.py
--- a/bot/response_policy.py
+++ b/bot/response_policy.py
@@ -1 +1 @@
-import re
+import re  # generated
```
"""
        patch = extract_unified_diff(text)
        self.assertTrue(patch.startswith("diff --git "))
        self.assertIn("bot/response_policy.py", patch)

    def test_rejects_protected_generated_patch(self):
        text = """diff --git a/config.py b/config.py
--- a/config.py
+++ b/config.py
@@ -1 +1 @@
-import os
+import sys
"""
        with self.assertRaisesRegex(ValueError, "violated policy"):
            extract_unified_diff(text)

    def test_rejects_prose_without_diff(self):
        with self.assertRaisesRegex(ValueError, "unified Git diff"):
            extract_unified_diff("I would change several files.")


if __name__ == "__main__":
    unittest.main()
