from services.memory_client import (
    OPENSEARCH_ENABLED,
    OPENSEARCH_INDEX,
    OS_HOST,
    OS_PASS,
    OS_USER,
    OS_VERIFY,
    conversation_key,
    ensure_index,
    index_message,
    init_es_client,
    runtime,
)
from services.memory_queries import (
    build_message_window,
    build_timeline_from_docs,
    build_timeline_prompt_block,
    fetch_matches_recent,
    fetch_recent_page,
    fetch_recent_timeline,
    get_newest_indexed_message_id,
    get_oldest_indexed_message_id,
    search_history_for_context,
)

__all__ = [
    "OPENSEARCH_ENABLED",
    "OPENSEARCH_INDEX",
    "OS_HOST",
    "OS_PASS",
    "OS_USER",
    "OS_VERIFY",
    "build_message_window",
    "build_timeline_from_docs",
    "build_timeline_prompt_block",
    "conversation_key",
    "ensure_index",
    "fetch_matches_recent",
    "fetch_recent_page",
    "fetch_recent_timeline",
    "get_newest_indexed_message_id",
    "get_oldest_indexed_message_id",
    "index_message",
    "init_es_client",
    "runtime",
    "search_history_for_context",
]
